elasticsearch:
  cluster:
    name: elasticsearch
  address:
    host: ${ELASTIC_ADDRESS_HOST:localhost}
    port: ${ELASTIC_ADDRESS_PORT:9200}
    username: ${ELASTIC_USERNAME:elastic}
    password: ${ELASTIC_PASSWORD:dome_2024!}
    ssl:
      enabled: false
      verification: false
spring:
  security:
    user:
      name: admin
      password: admin
# Spring Management Configuration - Actuator
management:
  server:
    port: 9000
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    probes:
      enabled: true

logging:
  level:
    it.eng.dome: ${LOG_LEVEL:DEBUG}
    org.apache.coyote.http11: ERROR

dome:
  tmforum:
    service-catalog-url: ${TMFORUM_SERVICE_CATALOG_URL:https://dome-dev.eng.it/tmf-api/serviceCatalogManagement/v4}
    product-catalog-url: ${TMFORUM_PRODUCT_CATALOG_URL:https://dome-dev.eng.it/tmf-api/productCatalogManagement/v4}
    resource-catalog-url: ${TMFORUM_RESOURCE_CATALOG_URL:https://dome-dev.eng.it/tmf-api/resourceCatalog/v4}

  # THIS MUST BE REMOVED IN THE FUTURE!!!
  bae:
    url: ${BAE_URL:https://dome-marketplace-prd.org}

  classify:
    url: ${CLASSIFY_URL:https://deployenv6.expertcustomers.ai:8086/services/dome/classify}
  
  analyze:
    url: ${ANALYZE_URL:https://deployenv6.expertcustomers.ai:8086/services/dome/analyze}
