
# Spring Configuration
server: 
  port: 8080
  servlet:
    context-path:  /

elasticsearch:
  cluster:
    name: elasticsearch
  address:
    host: ${ELASTIC_ADDRESS_HOST:localhost}
    port: ${ELASTIC_ADDRESS_PORT:9200}
    username: ${ELASTIC_USERNAME:elastic}
    password: ${ELASTIC_PASSWORD:dome_2024!}
    ssl:
      enabled: false
      verification: false
spring:
  security:
    user:
      name: admin
      password: admin
# Spring Management Configuration - Actuator
management:
  server:
    port: 9000
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    probes:
      enabled: true

logging:
  level:
    it.eng.dome: ${LOG_LEVEL:DEBUG}
    org.apache.coyote.http11: ERROR

tmforumapi:
  tmf_endpoint: ${TMF_ENDPOINT:https://tmf.dome-marketplace-sbx.org}
  tmf_envoy:  ${TMF_ENVOY:true}
  # valid only if envoy false
  tmf_namespace: ${TMF_NAMESPACE:marketplace}
  tmf_postfix:  ${TMF_POSTFIX:svc.cluster.local}
  tmf_port:  ${TMF_PORT:8080}

  tmf620_catalog_path: tmf-api/productCatalogManagement/v4
  tmf632_party_management_path: tmf-api/party/v4
  tmf633_service_catalog_path: tmf-api/serviceCatalogManagement/v4
  tmf634_resource_catalog_path: tmf-api/resourceCatalog/v4

dome:
  classify:
    url: ${CLASSIFY_URL:https://deployenv6.expertcustomers.ai:8086/services/dome/classify}
  
  analyze:
    url: ${ANALYZE_URL:https://deployenv6.expertcustomers.ai:8086/services/dome/analyze}
