elasticsearch:
  cluster:
    name: elasticsearch
  address:
    host: ${ELASTIC_ADDRESS_HOST:localhost}
    port: ${ELASTIC_ADDRESS_PORT:9200}
    username: ${ELASTIC_USERNAME:elastic}
    password: ${ELASTIC_PASSWORD:dome_2024!}
    ssl:
      enabled: false
      verification: false
spring:
  security:
    user:
      name: admin
      password: admin
# Spring Management Configuration - Actuator
management:
  server:
    port: 9000
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    probes:
      enabled: true

logging:
  level:
    it.eng.dome: ${LOG_LEVEL:INFO}

dome:
  tmforum:
    url: ${TMFORUM_URL:https://dome-dev.eng.it/tmf-api}

  # THIS MUST BE REMOVED IN THE FUTURE!!!
  bae:
    url: ${BAE_URL:https://dome-marketplace.org}
