elasticsearch:
  cluster:
    name: elasticsearch
  address:
    host: ${ELASTIC_ADDRESS_HOST:localhost}
    port: ${ELASTIC_ADDRESS_PORT:9200}
    username: ${ELASTIC_USERNAME:elastic}
    password: ${ELASTIC_PASSWORD:dome_2024!}
    ssl:
      enabled: false
      verification: false
spring:
  security:
    user:
      name: admin
      password: admin
# Spring Management Configuration - Actuator
management:
  server:
    port: 9000
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    probes:
      enabled: true

logging:
  level:
    it.eng.dome: ${LOG_LEVEL:DEBUG}

dome:
  tmforum:
    service-catalog-url: ${TMFORUM_SERVICE_CATALOG_URL:http://tm-forum-api-service-catalog.marketplace.svc.cluster.local:8080}
    product-catalog-url: ${TMFORUM_PRODUCT_CATALOG_URL:http://tm-forum-api-product-catalog.marketplace.svc.cluster.local:8080}
    resource-catalog-url: ${TMFORUM_RESOURCE_CATALOG_URL:http://tm-forum-api-resource-catalog.marketplace.svc.cluster.local:8080}

  # THIS MUST BE REMOVED IN THE FUTURE!!!
  bae:
    url: ${BAE_URL:http://bae-marketplace-biz-ecosystem-logic-proxy.marketplace.svc.cluster.local:8004}