elasticsearch:
  cluster:
    name: elasticsearch
  address:
    host: ${ELASTIC_HOST:localhost}
    port: ${ELASTIC_PORT:9200}
    username: ${ELASTIC_USERNAME:elastic}
    password: ${ELASTIC_PASSWORD:dome_2024!}
    ssl:
      enabled: false
      verification: false
spring:
  security:
    user:
      name: admin
      password: admin
# Spring Management Configuration - Actuator
management:
  server:
    port: 9000
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    probes:
      enabled: true

dome:
  getproductofferingbyid: https://dome-marketplace.org/catalog/productOffering
  getproductspecificationbyid: https://dome-marketplace.org/catalog/productSpecification
  getservicespecificationbyid: https://dome-marketplace.org/service/serviceSpecification
  getresourcespecificationbyid: https://dome-marketplace.org/resource/resourceSpecification
  getallproductofferings: https://dome-marketplace.org/catalog/productOffering
  gettmfallproductofferings: https://dome-dev.eng.it/tmf-api/productCatalogManagement/v4/productOffering
  gettmfproductofferingbyid: https://dome-dev.eng.it/tmf-api/productCatalogManagement/v4/productOffering
  gettmfproductspecificationbyid: https://dome-dev.eng.it/tmf-api/productCatalogManagement/v4/productSpecification
  gettmfservicespecificationbyid: https://dome-dev.eng.it/tmf-api/serviceCatalogManagement/v4/serviceSpecification
  gettmfresourcespecificationbyid: https://dome-dev.eng.it/tmf-api/resourceCatalog/v4/resourceSpecification
