version: '2.1'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
        container_name: elasticsearch
        volumes:
          - elasticsearch-data:/usr/share/elasticsearch/data/
        ports:
          - 9200:9200
          - 9300:9300
        environment:
          - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
          - discovery.type=single-node
          - cluster.name=elasticsearch

volumes:
    elasticsearch-data: