
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
        container_name: elasticsearch
        hostname: elasticsearch
        volumes:
          - elasticsearch-data:/usr/share/elasticsearch/data/
        ports:
          - ${ELASTICSEARCH_ADDRESS_PORT}:9200  
        environment:
          - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
          - discovery.type=single-node
          - cluster.name=elasticsearch
        #  - xpack.security.enabled=false
        #  - xpack.security.enrollment.enabled=false
          - xpack.security.http.ssl.enabled=false
          - ELASTIC_USERNAME=${ELASTIC_USERNAME}
          - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
        healthcheck:
          test:
            [
              "CMD-SHELL",
              "curl -s --user ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD} -X GET http://localhost:9200/_cluster/health?pretty | grep status | grep -q '\\(green\\|yellow\\)'",
            ]
          interval: 10s
          timeout: 10s
          retries: 5

volumes:
    elasticsearch-data: