
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
        container_name: elasticsearch
        hostname: elasticsearch
        volumes:
          - elasticsearch-data:/usr/share/elasticsearch/data/
        ports:
          - 9200:9200  
        environment:
          - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
          - discovery.type=single-node
          - cluster.name=elasticsearch
        #  - xpack.security.enabled=false
        #  - xpack.security.enrollment.enabled=false
          - xpack.security.http.ssl.enabled=false
          - ELASTIC_USERNAME=elastic
          - ELASTIC_PASSWORD=dome_2024!
        healthcheck:
          test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
          interval: 10s
          timeout: 10s
          retries: 5

volumes:
    elasticsearch-data: