
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
        container_name: elasticsearch
        hostname: elasticsearch
        volumes:
          - elasticsearch-data:/usr/share/elasticsearch/data/
          - ./certs:/usr/share/elasticsearch/config/certs
        ports:
          - ${ELASTIC_ADDRESS_PORT}:9200  
        environment:
          - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
          - discovery.type=single-node
          - cluster.name=elasticsearch
          - xpack.security.enabled=true
          - ELASTIC_USERNAME=${ELASTIC_USERNAME}
          - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

          - xpack.security.http.ssl.enabled=true
          - xpack.security.http.ssl.key=certs/elasticsearch/elasticsearch.key
          - xpack.security.http.ssl.certificate=certs/elasticsearch/elasticsearch.crt
          - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt

          - xpack.security.transport.ssl.enabled=true
          - xpack.security.transport.ssl.key=certs/elasticsearch/elasticsearch.key
          - xpack.security.transport.ssl.certificate=certs/elasticsearch/elasticsearch.crt
          - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt

        healthcheck:
          test:
            [
              "CMD-SHELL",
              "curl -s --user ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD} -X GET https://localhost:9200/_cluster/health?pretty | grep status | grep -q '\\(green\\|yellow\\)'"
            ]
          interval: 10s
          timeout: 10s
          retries: 5

volumes:
    elasticsearch-data: