version: '2.1'
services:
    search:
        image:
        container_name: search
        ports:
          - 8080:8080
        environment:
          - ELASTICSEARCH_ADDRESS_HOST=elasticsearch
          - ELASTICSEARCH_ADDRESS_PORT=9200
        depends_on:
          - elasticsearch
        
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
        container_name: elasticsearch
        volumes:
          - elasticsearch-data:/usr/share/elasticsearch/data/
        ports:
          - 9200:9200
          - 9300:9300
        environment:
          - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
          - discovery.type=single-node
          - cluster.name=elasticsearch

volumes:
    elasticsearch-data: