
name: Release Harbor

on:
  push:
    branches: ["harbor"]

env:
  #IMAGE_NAME: ${{ github.repository }} # github.repository => <user>/<repo>
  #IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/search
  IMAGE_NAME: search
  #IMAGE_VERSION: 0.0.${{ github.run_number }}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  pmd_job:
    name: Static Code Analyzer
    runs-on: ubuntu-latest  
    needs: [build]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
     
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Generate PMD report
        id: generate-pmd-report
        uses: pmd/pmd-github-action@v2
        with:
          rulesets: 'src/main/resources/rulesets/java/pmd-dome.xml'
          sourcePath: 'src/main/java'
          analyzeModifiedFilesOnly: false
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif

      - name: Fail build if there are violations
        if: steps.generate-pmd-report.outputs.violations > 0
        run: exit 1

  publish:
    name: Publish in Harbor repository
    runs-on: ubuntu-latest
    needs: [pmd_job]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      - run: mvn -B package --file pom.xml -DskipTests

      - name: Get Image Version
        run: |
          mvn versions:set -DremoveSnapshot -DgenerateBackupPoms=false -DinteractiveMode=false
          echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"
        id: getVersion

      - name: Print Image Version
        run: |
          echo "The image version is ${{ steps.getVersion.outputs.version }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: production.eng.it:8433
          username: robot-dome+dome-account
          password: AdzVCx7NnSbcAvdmxFvUi00gCSCwQM2g

      - name: Build and tag image
        run: |
          ls -al
          docker build -t production.eng.it:8433/dome/${{ env.IMAGE_NAME }}:${{ steps.getVersion.outputs.version }} .    
      
      - name: Push image to Harbor
        run: docker push production.eng.it:8433/dome/${{ env.IMAGE_NAME }}:${{ steps.getVersion.outputs.version }}
      

