name: Deploy with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  #IMAGE_NAME: ${{ github.repository }} # github.repository => <user>/<repo>
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/search-test-dome
  #IMAGE_VERSION: 0.0.${{ github.run_number }}
  IMAGE_VERSION: 0.0.5

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  pmd_job:
    name: Analyse Source Code with PMD
    runs-on: ubuntu-latest  
    needs: [build]

    steps:
      - uses: actions/checkout@v4
      # Run checks
      - name: PMD checks
        id: pmd-checks
        uses: rody/pmd-gh-action 

  publish:
    name: Publish in Docker Hub
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      - run: mvn -B package --file pom.xml -DskipTests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
